version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    - copyloopvar
    - goconst
    - godot
    - grouper
    - misspell
    - promlinter
    - sloglint
    - staticcheck
    - unparam
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
