title: otel-kafka
description: >-
  otel-kafka is an OpenTelemetry instrumentation library designed for confluent-kafka-go applications.
  It provides observability by integrating with the OpenTelemetry framework, allowing for the collection
  of traces and metrics related to Kafka operations. This enables better monitoring, troubleshooting,
  and performance analysis of Kafka-based systems.
theme: just-the-docs
url: https://otel-kafka.github.io
aux_links:
  confluent-kafka-go:
    - "//github.com/confluent-kafka-go"
  otel-kafka:
    - "//github.com/ekazakas/otel-kafka"